from fpdf import FPDF
from flask import make_response
import datetime

def generate_pdf(data):
    try:
        pdf = FPDF()
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(30, 144, 255)
        pdf.cell(0, 15, "LifeGuard AI - Health Risk Report", ln=True, align="C")

        # Date
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 8, f"Generated on: {datetime.datetime.now().strftime('%d %B %Y')}", ln=True, align="C")
        pdf.ln(5)

        # User Info
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "User Profile", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, f"Age: {data.get('age', 'N/A')}     Gender: {str(data.get('gender', 'N/A')).capitalize()}     Stage: {data.get('stage', 1)}", ln=True)
        pdf.ln(5)

        # Risk Results
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, "Disease Risk Scores", ln=True)
        pdf.set_font("Helvetica", "", 11)

        results = data.get("results", {})
        for disease in ["diabetes", "heart", "bp"]:
            d     = results.get(disease, {})
            name  = disease.upper() if disease != "bp" else "BLOOD PRESSURE"
            score = d.get("total_score", 0)
            risk  = d.get("risk", "N/A")
            pdf.cell(0, 9, f"{name}: Score {score}  ->  {risk}", ln=True)

        pdf.ln(5)

        # Advice
        advice = data.get("advice", "")
        if advice:
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 10, "Personalized Health Advice", ln=True)
            pdf.set_font("Helvetica", "", 10)
            # Clean the text
            clean_advice = advice.encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 7, clean_advice)
            pdf.ln(5)

        # Disclaimer
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(150, 150, 150)
        pdf.multi_cell(0, 6, "Disclaimer: This report is generated by an AI system and is not a medical diagnosis. Please consult a qualified doctor for proper medical advice.")

        # Return as Flask response
        pdf_bytes = bytes(pdf.output())
        response  = make_response(pdf_bytes)
        response.headers["Content-Type"]        = "application/pdf"
        response.headers["Content-Disposition"] = "attachment; filename=LifeGuard_Report.pdf"
        return response

    except Exception as e:
        print(f"PDF error: {e}")
        from flask import jsonify
        return jsonify({"error": str(e)}), 500